{% set name = "libaio" %}
{% set version = "0.8.3" %}

package:
  name: python-{{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a2ba7844ad1a4d32a947fb960c539779332bbe630019c246182d03f72c3d275b


build:
  # the python package is noarch, but requires an a linux only package.
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - libaio

test:
  imports:
    - libaio
  commands:
    - python -m libaio.test -vv

about:
  home: https://github.com/vpelletier/python-libaio
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING.LESSER
  summary: Python wrapper for libaio
  description: |
    Linux AIO API wrapper

    This is about in-kernel, file-descriptor-based asynchronous I/O. It has
    nothing to do with the asyncio standard module.

extra:
  recipe-maintainers:
    - hmaarrfk
