{% set name = "libaio" %}
{% set version = "0.9.1" %}

package:
  name: python-{{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9ee293a95ee56568b714922c2308878474b4ea9d05e7f4ba1e5e49873494b95d


build:
  # the python package is noarch, but requires an a linux only package.
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - libaio

test:
  imports:
    - libaio
  commands:
    - python -m libaio.test -vv

about:
  home: https://github.com/vpelletier/python-libaio
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING.LESSER
  summary: Python wrapper for libaio
  description: |
    Linux AIO API wrapper

    This is about in-kernel, file-descriptor-based asynchronous I/O. It has
    nothing to do with the asyncio standard module.

extra:
  recipe-maintainers:
    - hmaarrfk
