{% set name = "libaio" %}
{% set version = "0.8" %}

package:
  name: python-{{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 370f15fd2d3d86da59b4a5034d1f6bdfb710693586a0f7ac8f7c29a29400a738


build:
  # the python package is noarch, but requires an a linux only package.
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - libaio

test:
  imports:
    - libaio
  commands:
    - python -m libaio.test

about:
  home: https://github.com/vpelletier/python-libaio
  license: LGPL-3.0
  license_family: LGPL
  license_file: COPYING.LESSER
  summary: Python wrapper for libaio
  description: |
    Linux AIO API wrapper

    This is about in-kernel, file-descriptor-based asynchronous I/O. It has
    nothing to do with the asyncio standard module.

extra:
  recipe-maintainers:
    - hmaarrfk
