travis:
  secure:
    BINSTAR_TOKEN: DEMFpzYJO4AeePbJloXq8ljjvjTM0QKoGiAZHS0orbfZymLbEat96LEcG80Hkb4XKlGYNw7SJ/DFS00Hi+7TclbuUo7uXb7PBe24Slo1eq498uKEUhAdHSRcg20kHK+mMDo1m7z1F2DCZmU87ERu+wRLe91HeB9ULSNzQdm9NcLi+YRD0NsUJ6T52E4V9/wrDEsy/k7fjX9owaq+tXbBhTG7XpW0zTFTWGLnuzo1kuosUC0YJw4pjGwWe5FBW4TUBr1FcitTz9XWbru2VdL/OAduqEm1VZJl6Qe40PJ5BQXmRTWLLE/Fh9HxniHIf4WGciLOPReNDhLu/Xp2ayOnWLUDMTmRtnvgpBJ36efWa7ShUi0Dbsbw8p5R18xE1f7KY3VGAPJiUFOHo0GlpSCllX9cLviGdcvj8r0dgqImgM+iv2b9tXg0aACiqKLPXW3+QXYENu7sOyrsfrb57ml7S0VuVrvvTGG6PpNo3V+kZxbH1hSJnb/RwAKZ9pdQAgTW2w+rx0+uNtjgJg8JI/yeXAxJDEbk2pfCyQyItW1OuAspIlKI63qmKocc494g5o7XY1nc/cqAAZFg+DCybak99z4H8EJrrp7YavWgMlFlHcFd6+J9UvQJLvXY+X8OhIabgx1WRp08dgm8mEX9wmLrTuD+MT5Eson9t4w9rUL7g9Q=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
